name: Cleanup old images

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: aidevtools
          package-type: container
          min-versions-to-keep: 3
          owner: sugarfreebytes
